# Generated by Django 4.1.5 on 2023-01-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="img",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
